apiVersion: v1
kind: Service
metadata:
  name: {{ include "rpkv.fullname" . }}-shard
  labels:
    {{- include "rpkv.labels" . | nindent 4 }}
    app.kubernetes.io/component: shard
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "rpkv.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: shard
